"use client";

import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  Check,
  Clipboard,
  FileCheck2,
  Info,
  Printer,
  RotateCcw,
} from "lucide-react";
import { AppSidebar } from "@/components/understand/AppSidebar";
import { UnderstandHeader } from "@/components/understand/UnderstandHeader";
import { Button } from "@/components/ui/Button";
import { useMatter } from "@/providers/MatterProvider";
import type { GuidanceResult, LegalSource, MatterContext, MatterFact, NextStep } from "@/types/matter";

type SupportingGroup = {
  title: string;
  items: MatterFact[];
};

export function SummaryWorkspace() {
  const router = useRouter();
  const { matter, setMatter } = useMatter();
  const [copied, setCopied] = useState(false);
  const [confirmNew, setConfirmNew] = useState(false);

  const guidance = matter?.guidance;
  const canRender =
    Boolean(matter && guidance) &&
    (matter?.stage === "GUIDANCE_GENERATED" || matter?.stage === "COMPLETED");

  useEffect(() => {
    if (!matter) {
      router.replace("/");
      return;
    }

    if (matter.stage === "UNDERSTANDING" || matter.stage === "NEEDS_CLARIFICATION") {
      router.replace("/understand");
      return;
    }

    if (matter.stage === "READY_FOR_REVIEW" || !matter.verifiedAt) {
      router.replace("/verify");
      return;
    }

    if (!matter.guidance) {
      router.replace("/guidance");
      return;
    }

    if (matter.stage === "GUIDANCE_GENERATED") {
      setMatter({
        ...matter,
        stage: "COMPLETED",
      });
    }
  }, [matter, router, setMatter]);

  const verifiedFacts = useMemo(
    () => matter?.facts.filter((fact) => fact.state !== "unknown") ?? [],
    [matter],
  );
  const supportingGroups = useMemo(() => buildSupportingGroups(verifiedFacts), [verifiedFacts]);
  const isIncidentSummary = useMemo(() => isIncidentMatter(matter), [matter]);

  if (!matter || !guidance || !canRender) {
    return (
      <main className="grid min-h-screen place-items-center bg-[#F7F3EA] px-5 text-[#18150F]">
        <section className="max-w-xl rounded-lg border border-[#DED7CA] bg-[#FBF8F1] p-6">
          <p className="text-sm font-extrabold uppercase text-[#A8752B]">Summary gate</p>
          <h1 className="font-editorial mt-3 text-4xl font-bold text-[#071B3A]">
            Preparing the correct step
          </h1>
          <p className="mt-3 text-sm font-semibold leading-6 text-[#6B665D]">
            NyayaSaarthi is taking you back to the step needed for this matter.
          </p>
        </section>
      </main>
    );
  }

  async function handleCopySummary() {
    if (!matter || !guidance) {
      return;
    }

    const text = buildPlainTextSummary(matter, guidance, verifiedFacts);

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      setCopied(false);
    }
  }

  function handlePrint() {
    // Prototype export uses browser print/save-to-PDF.
    // Production export can later be generated by the backend.
    window.print();
  }

  function handleStartNew() {
    setMatter(null);
    router.push("/");
  }

  return (
    <div className="summary-page min-h-screen bg-[#F7F3EA] text-[#18150F] lg:grid lg:grid-cols-[248px_1fr]">
      <AppSidebar currentStep="summary" />
      <div className="min-w-0">
        <UnderstandHeader language={matter.language} currentStep="summary" />
        <main className="px-4 py-5 sm:px-6 lg:px-8">
          <div className="summary-document mx-auto max-w-[1040px]">
            <header className="rounded-lg border border-[#DED7CA] bg-[#FBF8F1] px-5 py-6 sm:px-7">
              <div className="flex flex-wrap items-center gap-2">
                <span className="inline-flex items-center gap-2 rounded-md border border-[#647567]/35 bg-[#EEF5ED] px-3 py-1 text-xs font-extrabold uppercase text-[#35533A]">
                  <Check size={14} aria-hidden="true" />
                  Guidance Complete
                </span>
                <span className="inline-flex rounded-md border border-[#C49A55]/60 bg-[#F4E8D3] px-3 py-1 text-xs font-extrabold uppercase text-[#7A521F]">
                  Matter Summary
                </span>
              </div>
              <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_auto] lg:items-end">
                <div>
                  <h1 className="font-editorial text-4xl font-bold leading-tight text-[#18150F] sm:text-5xl">
                    {isIncidentSummary ? "Structured Situation & Guidance Summary" : "Your Guidance Summary"}
                  </h1>
                  <p className="mt-3 max-w-3xl text-sm font-semibold leading-6 text-[#6B665D] sm:text-base">
                    A structured record of the situation you verified, the legal information matched
                    to it, and the recommended next steps.
                  </p>
                </div>
                <dl className="grid min-w-[260px] gap-2 rounded-md border border-[#DED7CA] bg-[#FFFDF8] p-4 text-sm">
                  <MetaRow label="Created" value={formatDate(matter.createdAt)} />
                  <MetaRow label="Language" value={formatLanguage(matter.language)} />
                  <MetaRow label="Matter" value={matter.intent.label} />
                </dl>
              </div>
            </header>

            <section className="summary-actions mt-5 rounded-lg border border-[#DED7CA] bg-[#071B3A] p-5 text-white sm:p-6">
              <div className="grid gap-5 md:grid-cols-[1fr_auto] md:items-center">
                <div>
                  <p className="text-xs font-extrabold uppercase text-[#C49A55]">
                    Your NyayaSaarthi summary is ready.
                  </p>
                  <p className="mt-2 max-w-2xl text-sm font-semibold leading-6 text-[#E8DDCC]">
                    This record brings together the facts you verified, relevant legal guidance,
                    remaining uncertainty and the actions you may want to take next.
                  </p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Button className="border-[#C49A55] bg-[#C49A55] text-[#071B3A] hover:border-[#D7AD69] hover:bg-[#D7AD69]" onClick={handlePrint}>
                    <Printer size={16} aria-hidden="true" />
                    Print / Save as PDF
                  </Button>
                  <Button variant="secondary" className="border-white/20 bg-white/10 text-white hover:border-[#C49A55] hover:text-white" onClick={handleCopySummary}>
                    <Clipboard size={16} aria-hidden="true" />
                    {copied ? "Copied" : "Copy Summary"}
                  </Button>
                </div>
              </div>
            </section>

            <div className="mt-5 space-y-5">
              <SummarySection number="01" title="Matter Overview">
                <div className="grid gap-4 md:grid-cols-2">
                  <MetaBlock label="Matter Type" value={matter.intent.label} />
                  <MetaBlock label="Created" value={formatDate(matter.createdAt)} />
                  <MetaBlock label="Language" value={formatLanguage(matter.language)} />
                  <MetaBlock label="Status" value="Guidance Complete" />
                </div>
                <div className="mt-5 border-t border-[#DED7CA] pt-4">
                  <p className="text-xs font-extrabold uppercase text-[#6B665D]">Original Question</p>
                  <p className="mt-2 text-base font-semibold leading-7 text-[#18150F]">
                    “{matter.originalText}”
                  </p>
                </div>
              </SummarySection>

              <SummarySection number="02" title="What You Told Us">
                <div className="grid gap-x-8 gap-y-4 sm:grid-cols-2">
                  {verifiedFacts.map((fact) => (
                    <FactLine key={fact.id} fact={fact} />
                  ))}
                </div>
              </SummarySection>

              <SummarySection number="03" title="What NyayaSaarthi Identified">
                <div className="grid gap-4 md:grid-cols-3">
                  <MetaBlock label="Potential Issue" value={matter.intent.label} />
                  <MetaBlock label="Relevant Context" value={buildRelevantContext(verifiedFacts)} />
                  <MetaBlock label="Legal Area" value={matter.intent.descriptor} />
                </div>
              </SummarySection>

              <SummarySection number="04" title="Guidance">
                <div className="grid gap-4">
                  <LabeledParagraph label="NyayaSaarthi Explanation" text={guidance.directAnswer} />
                  <LabeledParagraph label="Qualification" text={guidance.qualification} muted />
                </div>
              </SummarySection>

              <SummarySection number="05" title="Why This Guidance Was Given">
                <div className="space-y-3">
                  {guidance.mappings.slice(0, 3).map((mapping) => (
                    <article key={mapping.id} className="rounded-md border border-[#DED7CA] bg-[#FFFDF8] p-4">
                      <div className="grid gap-3 lg:grid-cols-[1fr_1fr_1.25fr]">
                        <MappingCell label="Your Verified Fact" value={mapping.fact} />
                        <MappingCell label="Relevant Official Rule" value={mapping.sourceTitle} />
                        <MappingCell label="NyayaSaarthi Explanation" value={mapping.explanation} />
                      </div>
                    </article>
                  ))}
                </div>
              </SummarySection>

              <SummarySection number="06" title="Relevant Official Sources">
                <div className="space-y-3">
                  {guidance.sources.slice(0, 4).map((source) => (
                    <SourceRow key={source.id} source={source} />
                  ))}
                </div>
              </SummarySection>

              <SummarySection number="07" title="What Is Still Uncertain">
                <div className="rounded-md border border-[#DED7CA] bg-[#F7F0E3] p-4">
                  <div className="flex items-start gap-3">
                    <Info className="mt-0.5 shrink-0 text-[#A8752B]" size={18} aria-hidden="true" />
                    <div className="space-y-2">
                      {(guidance.uncertainties.length > 0
                        ? guidance.uncertainties
                        : ["No material unresolved context remains in the current guidance."]
                      ).map((item) => (
                        <p key={item} className="text-sm font-semibold leading-6 text-[#4F4A42]">
                          {item}
                        </p>
                      ))}
                    </div>
                  </div>
                </div>
              </SummarySection>

              <SummarySection number="08" title="Recommended Next Steps">
                <RecommendedActions steps={guidance.nextSteps} />
              </SummarySection>

              {supportingGroups.length > 0 ? (
                <SummarySection title="Supporting Information">
                  <div className="grid gap-4 md:grid-cols-2">
                    {supportingGroups.map((group) => (
                      <article key={group.title} className="rounded-md border border-[#DED7CA] bg-[#FFFDF8] p-4">
                        <h3 className="text-sm font-extrabold text-[#18150F]">{group.title}</h3>
                        <ul className="mt-3 space-y-2">
                          {group.items.map((item) => (
                            <li key={item.id} className="text-sm font-semibold leading-6 text-[#6B665D]">
                              <span className="font-extrabold text-[#18150F]">{item.label}:</span>{" "}
                              {item.value}
                            </li>
                          ))}
                        </ul>
                      </article>
                    ))}
                  </div>
                </SummarySection>
              ) : null}

              <SummarySection title="Information Source Key">
                <div className="grid gap-3 md:grid-cols-3">
                  <LegendItem title="You" text="Information you provided or confirmed." />
                  <LegendItem title="Official Source" text="Law, rule, notification or government guidance retrieved by NyayaSaarthi." />
                  <LegendItem title="NyayaSaarthi Explanation" text="Plain-language explanation generated from your verified context and retrieved sources." />
                </div>
              </SummarySection>

              <section className="summary-section rounded-lg border border-[#DED7CA] bg-[#FBF8F1] p-5 sm:p-6">
                <p className="text-sm font-semibold leading-6 text-[#6B665D]">
                  NyayaSaarthi provides informational guidance based on the situation you verified
                  and the legal sources retrieved. It does not replace professional legal advice or
                  an official determination by an authorised authority.
                </p>
              </section>

              <section className="summary-actions rounded-lg border border-[#DED7CA] bg-[#FBF8F1] p-5 sm:p-6">
                <div className="flex flex-wrap gap-3">
                  <Button onClick={handlePrint}>
                    <Printer size={16} aria-hidden="true" />
                    Print / Save as PDF
                  </Button>
                  <Button variant="secondary" onClick={handleCopySummary}>
                    <Clipboard size={16} aria-hidden="true" />
                    {copied ? "Copied" : "Copy Summary"}
                  </Button>
                  <Button variant="secondary" onClick={() => router.push("/guidance")}>
                    <ArrowLeft size={16} aria-hidden="true" />
                    Back to Guidance
                  </Button>
                  <Button variant="ghost" onClick={() => router.push("/verify")}>
                    <FileCheck2 size={16} aria-hidden="true" />
                    Edit Verified Situation
                  </Button>
                  <Button variant="ghost" onClick={() => setConfirmNew(true)}>
                    <RotateCcw size={16} aria-hidden="true" />
                    Start New Situation
                  </Button>
                </div>
              </section>
            </div>
          </div>
        </main>
      </div>

      {confirmNew ? (
        <div className="fixed inset-0 z-50 grid place-items-center bg-[#071B3A]/45 px-4">
          <section className="w-full max-w-md rounded-lg border border-[#DED7CA] bg-[#FBF8F1] p-5 shadow-xl">
            <h2 className="font-editorial text-3xl font-bold text-[#18150F]">Start a new situation?</h2>
            <p className="mt-2 text-sm font-semibold leading-6 text-[#6B665D]">
              This will clear the current frontend prototype matter.
            </p>
            <div className="mt-5 flex justify-end gap-3">
              <Button variant="secondary" onClick={() => setConfirmNew(false)}>
                Cancel
              </Button>
              <Button onClick={handleStartNew}>Start New</Button>
            </div>
          </section>
        </div>
      ) : null}
    </div>
  );
}

function SummarySection({
  number,
  title,
  children,
}: {
  number?: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="summary-section rounded-lg border border-[#DED7CA] bg-[#FBF8F1] p-5 sm:p-6">
      <div className="mb-4 flex items-baseline gap-3">
        {number ? (
          <span className="font-editorial text-2xl font-bold leading-none text-[#A8752B]">
            {number}
          </span>
        ) : null}
        <h2 className="font-editorial text-3xl font-bold leading-tight text-[#18150F]">{title}</h2>
      </div>
      {children}
    </section>
  );
}

function MetaRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="grid grid-cols-[72px_1fr] gap-3">
      <dt className="text-xs font-extrabold uppercase text-[#6B665D]">{label}</dt>
      <dd className="text-sm font-extrabold text-[#18150F]">{value}</dd>
    </div>
  );
}

function MetaBlock({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs font-extrabold uppercase text-[#6B665D]">{label}</p>
      <p className="mt-1 text-sm font-extrabold leading-6 text-[#18150F]">{value}</p>
    </div>
  );
}

function FactLine({ fact }: { fact: MatterFact }) {
  return (
    <div className="border-b border-[#DED7CA] pb-3">
      <div className="flex items-start justify-between gap-3">
        <p className="text-xs font-extrabold uppercase text-[#6B665D]">{fact.label}</p>
        <span className="shrink-0 rounded-md border border-[#DED7CA] bg-[#FFFDF8] px-2 py-1 text-[0.65rem] font-extrabold uppercase text-[#6B665D]">
          {provenanceLabel(fact)}
        </span>
      </div>
      <p className="mt-1 text-base font-extrabold leading-6 text-[#18150F]">{fact.value}</p>
    </div>
  );
}

function LabeledParagraph({ label, text, muted }: { label: string; text: string; muted?: boolean }) {
  return (
    <div className="rounded-md border border-[#DED7CA] bg-[#FFFDF8] p-4">
      <p className="text-xs font-extrabold uppercase text-[#A8752B]">{label}</p>
      <p className={`mt-2 text-base font-semibold leading-7 ${muted ? "text-[#4F4A42]" : "text-[#18150F]"}`}>
        {text}
      </p>
    </div>
  );
}

function MappingCell({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs font-extrabold uppercase text-[#6B665D]">{label}</p>
      <p className="mt-2 text-sm font-semibold leading-6 text-[#18150F]">{value}</p>
    </div>
  );
}

function SourceRow({ source }: { source: LegalSource }) {
  return (
    <article className="rounded-md border border-[#DED7CA] bg-[#FFFDF8] p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <p className="text-xs font-extrabold uppercase text-[#A8752B]">Official Source</p>
          <h3 className="mt-1 text-base font-extrabold text-[#18150F]">{source.title}</h3>
        </div>
        <span className="rounded-md border border-[#DED7CA] bg-[#F7F3EA] px-2 py-1 text-[0.68rem] font-extrabold uppercase text-[#6B665D]">
          {source.sourceType}
        </span>
      </div>
      <dl className="mt-4 grid gap-3 md:grid-cols-2">
        <MetaBlock label="Provision" value={source.provision ?? "Not specified in prototype"} />
        <MetaBlock label="Authority" value={source.authority} />
      </dl>
      <p className="mt-4 text-xs font-extrabold uppercase text-[#6B665D]">Why relevant</p>
      <p className="mt-1 text-sm font-semibold leading-6 text-[#4F4A42]">{source.relevantPoint}</p>
      {source.sourceUrl ? (
        <a className="mt-3 inline-flex items-center gap-2 text-sm font-extrabold text-[#071B3A]" href={source.sourceUrl}>
          View official source
        </a>
      ) : (
        <p className="mt-3 text-xs font-extrabold uppercase text-[#6B665D]">
          Official link unavailable in prototype
        </p>
      )}
    </article>
  );
}

function RecommendedActions({ steps }: { steps: NextStep[] }) {
  return (
    <div className="divide-y divide-[#DED7CA]">
      {steps.map((step, index) => (
        <article key={step.id} className="grid gap-3 py-4 first:pt-0 sm:grid-cols-[48px_1fr]">
          <span className="font-editorial text-3xl font-bold leading-none text-[#A8752B]">
            {String(index + 1).padStart(2, "0")}
          </span>
          <div>
            <div className="flex flex-wrap items-center gap-2">
              <h3 className="text-base font-extrabold text-[#18150F]">{step.title}</h3>
              <span className="rounded-md border border-[#DED7CA] bg-[#FFFDF8] px-2 py-1 text-[0.68rem] font-extrabold uppercase text-[#6B665D]">
                {step.tag}
              </span>
            </div>
            <p className="mt-1 text-sm font-semibold leading-6 text-[#6B665D]">{step.description}</p>
          </div>
        </article>
      ))}
    </div>
  );
}

function LegendItem({ title, text }: { title: string; text: string }) {
  return (
    <div className="rounded-md border border-[#DED7CA] bg-[#FFFDF8] p-4">
      <p className="text-sm font-extrabold text-[#18150F]">{title}</p>
      <p className="mt-1 text-sm font-semibold leading-6 text-[#6B665D]">{text}</p>
    </div>
  );
}

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-IN", {
    day: "numeric",
    month: "short",
    year: "numeric",
  }).format(new Date(value));
}

function formatLanguage(value: MatterContext["language"]) {
  if (value === "auto") {
    return "Auto-detected";
  }

  return value.charAt(0).toUpperCase() + value.slice(1);
}

function provenanceLabel(fact: MatterFact) {
  if (fact.provenance === "USER_CONFIRMED") {
    return fact.state === "confirmed" ? "You confirmed" : "Confirmed";
  }

  if (fact.provenance === "USER_PROVIDED") {
    return "You provided";
  }

  if (fact.provenance === "SYSTEM_INFERRED") {
    return "System inferred";
  }

  return "Unknown";
}

function buildRelevantContext(facts: MatterFact[]) {
  const labels = facts.slice(0, 5).map((fact) => fact.label.toLowerCase());
  return labels.length > 0 ? labels.join(" + ") : "Verified matter context";
}

function isIncidentMatter(matter: MatterContext | null) {
  const text = `${matter?.intent.label ?? ""} ${matter?.intent.descriptor ?? ""} ${matter?.originalText ?? ""}`;
  return /accident|collision|hit-and-run|hit my car|injur|damage/i.test(text);
}

function buildSupportingGroups(facts: MatterFact[]): SupportingGroup[] {
  const groups = [
    {
      title: "Evidence Mentioned",
      patterns: [/evidence/i, /photo/i, /video/i, /dashcam/i, /damage/i, /document/i],
    },
    {
      title: "People / Witnesses",
      patterns: [/witness/i, /person/i, /people/i],
    },
    {
      title: "Vehicles",
      patterns: [/other vehicle/i, /vehicle detail/i, /number plate/i, /registration/i],
    },
    {
      title: "Insurance Information",
      patterns: [/insurance/i, /policy/i, /insurer/i],
    },
    {
      title: "Timeline",
      patterns: [/timeline/i, /time/i, /occurred/i],
    },
  ];

  return groups
    .map((group) => ({
      title: group.title,
      items: facts.filter((fact) =>
        group.patterns.some((pattern) => pattern.test(`${fact.id} ${fact.key} ${fact.label}`)),
      ),
    }))
    .filter((group) => group.items.length > 0);
}

function buildPlainTextSummary(
  matter: MatterContext,
  guidance: GuidanceResult,
  facts: MatterFact[],
) {
  return [
    "NyayaSaarthi Guidance Summary",
    "",
    "Original Question:",
    matter.originalText,
    "",
    "Verified Situation:",
    ...facts.map((fact) => `${fact.label}: ${fact.value}`),
    "",
    "Guidance:",
    guidance.directAnswer,
    guidance.qualification,
    "",
    "Relevant Sources:",
    ...guidance.sources.map((source) => `${source.title} - ${source.authority}`),
    "",
    "Remaining Uncertainty:",
    ...(guidance.uncertainties.length > 0
      ? guidance.uncertainties
      : ["No material unresolved context remains in the current guidance."]),
    "",
    "Recommended Actions:",
    ...guidance.nextSteps.map((step, index) => `${index + 1}. ${step.title}: ${step.description}`),
    "",
    "Disclaimer:",
    "NyayaSaarthi provides informational guidance based on the situation you verified and the legal sources retrieved. It does not replace professional legal advice or an official determination by an authorised authority.",
  ].join("\n");
}
